name: poseup_app
description: PoseUp 스마트 알람 및 AI 포즈 챌린지 앱
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.4.10
  go_router: ^14.1.4
  http: ^1.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

